// Code generated by go-bindata.
// sources:
// data/exercises.template.scm
// data/tests.template.scm
// DO NOT EDIT!

package pset

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataExercisesTemplateScm = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xd2\xc8\xc9\x4f\x4c\x51\x50\xaa\xae\xd6\x0b\x49\x2d\x2e\x29\x76\xcb\xcc\x49\xad\xad\x55\xd2\xe4\x42\x88\xbb\xa4\x16\xc0\x85\x01\x01\x00\x00\xff\xff\xd3\x62\x2a\x66\x2e\x00\x00\x00")

func dataExercisesTemplateScmBytes() ([]byte, error) {
	return bindataRead(
		_dataExercisesTemplateScm,
		"data/exercises.template.scm",
	)
}

func dataExercisesTemplateScm() (*asset, error) {
	bytes, err := dataExercisesTemplateScmBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/exercises.template.scm", size: 46, mode: os.FileMode(420), modTime: time.Unix(1461297835, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dataTestsTemplateScm = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x14\xca\x31\x0e\x80\x20\x0c\x05\xd0\xbd\xa7\x20\x4c\x30\xc8\x59\xbc\x02\x4a\x25\x24\x50\x12\xca\xd6\xfc\xbb\xab\xfb\x0b\x7d\xe6\xe2\xfc\x66\xdd\x4d\x6a\xd2\x7b\xf8\x48\x44\x66\x2b\x4b\x65\x97\xce\x35\xaf\xce\x43\x01\x0a\x85\x9f\x26\xec\xc2\x8f\x0f\xb3\x04\xc4\xf8\x49\x96\x02\xbc\x01\x00\x00\xff\xff\xb1\x87\x0b\x1d\x48\x00\x00\x00")

func dataTestsTemplateScmBytes() ([]byte, error) {
	return bindataRead(
		_dataTestsTemplateScm,
		"data/tests.template.scm",
	)
}

func dataTestsTemplateScm() (*asset, error) {
	bytes, err := dataTestsTemplateScmBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/tests.template.scm", size: 72, mode: os.FileMode(420), modTime: time.Unix(1461297879, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/exercises.template.scm": dataExercisesTemplateScm,
	"data/tests.template.scm": dataTestsTemplateScm,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"exercises.template.scm": &bintree{dataExercisesTemplateScm, map[string]*bintree{}},
		"tests.template.scm": &bintree{dataTestsTemplateScm, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

